# Generated by Django 5.0.4 on 2024-11-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="source",
            name="slug",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
