# Generated by Django 5.0.4 on 2024-11-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0002_alter_source_name_alter_source_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("message", models.TextField(db_index=True, null=True)),
                ("type", models.CharField(db_index=True, max_length=32)),
                ("obj_pk", models.CharField(db_index=True, max_length=255, null=True)),
                (
                    "obj_model",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                (
                    "obj_action",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ("obj_changes", models.JSONField(null=True)),
            ],
        ),
    ]
