# Generated by Django 5.1.5 on 2025-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0002_source_fields_groupby_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="context_fields",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
