# Generated by Django 5.1.5 on 2025-03-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0003_source_context_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="support_raw_query",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
