# Generated by Django 5.1.7 on 2025-04-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0006_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="date_field",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
