# Generated by Django 5.1.7 on 2025-10-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0011_migrate_connections_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="connection",
        ),
    ]
