# Generated by Django 5.1.7 on 2025-10-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0012_remove_source_connection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="table",
        ),
    ]
