# Generated by Django 5.1.7 on 2025-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0013_remove_source_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="execute_query_on_open",
            field=models.BooleanField(default=True),
        ),
    ]
