# Generated by Django 5.1.7 on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0017_migrate_savedview_data_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="severity_rules",
            field=models.JSONField(null=True, blank=True, default=None),
        ),
    ]
