{{- if and (eq .Values.database.type "sqlite") .Values.database.sqlite.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "telescope.fullname" . }}-sqlite
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telescope.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.sqlite.persistence.size }}
  {{- if .Values.database.sqlite.persistence.storageClass }}
  storageClassName: {{ .Values.database.sqlite.persistence.storageClass }}
  {{- end }}
{{- end }}