import zoneinfo


VIEW_SCOPE_PERSONAL = "personal"
VIEW_SCOPE_SOURCE = "source"
VIEW_KIND_SOURCE = "source"
VIEW_KIND_USER = "user"
VIEW_KIND_SHARED = "shared"
UTC_ZONE = zoneinfo.ZoneInfo("UTC")

LIMIT = [
    "10",
    "50",
    "100",
    "500",
    "1000",
    "5000",
    "10000",
    "25000",
]

SOURCE_KIND_CLICKHOUSE = "clickhouse"
SOURCE_KIND_DOCKER = "docker"
SOURCE_KIND_KUBERNETES = "kubernetes"

SUPPORTED_SOURCE_KINDS = {
    SOURCE_KIND_CLICKHOUSE,
    SOURCE_KIND_DOCKER,
    SOURCE_KIND_KUBERNETES,
}

SOURCE_SEVERITY_COL_NAME = "severity"
SOURCE_BODY_COL_NAME = "body"
SOURCE_QUERY_MODE_SEPARATE = "separate"
SOURCE_QUERY_MODE_COMBINED = "combined"
SOURCE_CAPABILITY_RAW_QUERY = "raw_query"
SOURCE_CAPABILITY_SEVERITY_RULES = "severity_rules"
SOURCE_CAPABILITY_NORMALIZE_BODY = "normalize_body"
SOURCE_CAPABILITY_QUERY_MODE = "query_mode"

SOURCE_CAPABILITIES = {
    SOURCE_KIND_CLICKHOUSE: {
        SOURCE_CAPABILITY_RAW_QUERY: True,
        SOURCE_CAPABILITY_SEVERITY_RULES: False,
        SOURCE_CAPABILITY_NORMALIZE_BODY: False,
        SOURCE_CAPABILITY_QUERY_MODE: "separate",
    },
    SOURCE_KIND_DOCKER: {
        SOURCE_CAPABILITY_RAW_QUERY: False,
        SOURCE_CAPABILITY_SEVERITY_RULES: True,
        SOURCE_CAPABILITY_NORMALIZE_BODY: True,
        SOURCE_CAPABILITY_QUERY_MODE: "combined",
    },
    SOURCE_KIND_KUBERNETES: {
        SOURCE_CAPABILITY_RAW_QUERY: False,
        SOURCE_CAPABILITY_SEVERITY_RULES: True,
        SOURCE_CAPABILITY_NORMALIZE_BODY: True,
        SOURCE_CAPABILITY_QUERY_MODE: "combined",
    },
}
