def get_docker_source_data(slug):
    return {
        "kind": "docker",
        "slug": slug,
        "name": "Docker",
        "description": "docker test source",
        "time_field": "time",
        "uniq_field": "",
        "severity_field": "",
        "fields": {
            "time": {
                "display_name": "",
                "type": "datetime",
                "autocomplete": False,
                "suggest": True,
                "jsonstring": False,
                "group_by": False,
                "values": [],
            },
            "container_id": {
                "display_name": "",
                "type": "string",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "container_name": {
                "display_name": "",
                "type": "string",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "container_short_id": {
                "display_name": "",
                "type": "string",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "message": {
                "display_name": "IsMessage",
                "type": "string",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": True,
                "group_by": True,
                "values": [],
            },
            "status": {
                "display_name": "",
                "type": "string",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "stream": {
                "display_name": "",
                "type": "string",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "labels": {
                "display_name": "",
                "type": "string",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
        },
        "support_raw_query": False,
        "default_chosen_fields": "container_short_id, stream, message",
        "connection": {"address": "unix:///var/run/docker.sock"},
    }


def get_clickhouse_source_data(slug, kind="clickhouse"):
    return {
        "kind": kind,
        "slug": slug,
        "name": "ClickHouse",
        "description": "clickhouse test source",
        "time_field": "event_time",
        "date_field": "event_date",
        "uniq_field": "",
        "severity_field": "query_kind",
        "fields": {
            "hostname": {
                "display_name": "",
                "type": "LowCardinality(String)",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "event_date": {
                "display_name": "",
                "type": "Date",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "event_time": {
                "display_name": "",
                "type": "DateTime64(3)",
                "autocomplete": False,
                "suggest": True,
                "jsonstring": False,
                "group_by": False,
                "values": [],
            },
            "event_time_microseconds": {
                "display_name": "",
                "type": "DateTime64(6)",
                "autocomplete": False,
                "suggest": True,
                "jsonstring": False,
                "group_by": False,
                "values": [],
            },
            "thread_name": {
                "display_name": "",
                "type": "LowCardinality(String)",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "thread_id": {
                "display_name": "",
                "type": "UInt64",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "level": {
                "display_name": "",
                "type": "Enum8('Fatal' = 1, 'Critical' = 2, 'Error' = 3, 'Warning' = 4, 'Notice' = 5, 'Information' = 6, 'Debug' = 7, 'Trace' = 8, 'Test' = 9)",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [
                    "Fatal",
                    "Critical",
                    "Error",
                    "Warning",
                    "Notice",
                    "Information",
                    "Debug",
                    "Trace",
                    "Test",
                ],
            },
            "query_id": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "logger_name": {
                "display_name": "",
                "type": "LowCardinality(String)",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "message": {
                "display_name": "IsMessage",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": True,
                "group_by": True,
                "values": [],
            },
            "revision": {
                "display_name": "",
                "type": "UInt32",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "source_file": {
                "display_name": "",
                "type": "LowCardinality(String)",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "source_line": {
                "display_name": "",
                "type": "UInt64",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "message_format_string": {
                "display_name": "",
                "type": "LowCardinality(String)",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value1": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value2": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value3": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value4": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value5": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value6": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value7": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value8": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value9": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
            "value10": {
                "display_name": "",
                "type": "String",
                "autocomplete": True,
                "suggest": True,
                "jsonstring": False,
                "group_by": True,
                "values": [],
            },
        },
        "default_chosen_fields": "hostname, query",
        "connection": {
            "host": "localhost",
            "port": 9440,
            "user": "default",
            "password": "testpwd",
            "database": "logs",
            "table": "logs",
            "ssl": True,
            "verify": True,
            "ca_certs": "",
            "certfile": "",
            "keyfile": "",
            "ssl_version": "",
            "ciphers": "",
            "server_hostname": "",
            "alt_hosts": "",
        },
    }


def get_saved_view_data():
    return {
        "fields": "message",
        "query": "",
        "from": "now",
        "to": "now-5m",
        "limit": 50,
        "graph_group_by": "",
        "show_graph": True,
        "context_fields": {},
    }
